# vi: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - ansible_distribution == 'Ubuntu'

- name: set OS specific variables
  include_vars:
    file: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
...
